Repository rt-net/RaspberryPiMouse, pull requests merged in 2020-04, with the labels that each got.

#33 Fix error check of motor class_creates
  src/drivers/rtmouse.c
Labels: bug/不具合

#32 Add step4, step5 samples
  SampleProgram/README.md
  SampleProgram/step4.c
  SampleProgram/step4.py
  SampleProgram/step4.sh
  SampleProgram/step5.c
  SampleProgram/step5.py
  SampleProgram/step5.sh
Labels: enhancement/機能追加

#35 Add signed counter (rtcounter_l1, rtcounter_r1)
  src/drivers/rtmouse.c
Labels: enhancement/機能追加

#41 Add step6 sample
  SampleProgram/README.md
  SampleProgram/step6.c
  SampleProgram/step6.py
  SampleProgram/step6.sh
Labels: enhancement/機能追加

#43 インストール方法を更新してRaspberry Pi 4について追記
  README.md
Labels: documentation/ドキュメント

#44 Migrate to GitHub Actions
  .github/workflows/driver-cross-build.yml
  .travis.yml
  README.md
Labels: ci
