Repository rt-net/RaspberryPiMouse, pull requests merged in 2020-07, with the labels that each got.

#57 Change license from GPLv3 to GPLv2
  LICENSE
  README.md
  src/drivers/rtmouse.c
Labels: Type: Breaking Change, Type: Maintenance

#59 Update README.md
  README.md
Labels: Type: Documentation

#60 Fix step1.py
  SampleProgram/step1.py
Labels: Type: Maintenance
