Repository rt-net/RaspberryPiMouse, pull requests merged in 2021-07, with the labels that each got.

#71 Use kstrtoint_from_user() instead of parseFreq() and parse_count() to detect parse error.
  src/drivers/rtmouse.c
Labels: Type: Bug

#72 Reset uncontrollable motor frequency to zero.
  README.md
  src/drivers/rtmouse.c
Labels: Type: Feature

#70 Add Lint CI config
  .github/workflows/driver-cross-build.yml
  .test/bin/run-clang-format.py
  .test/lint.sh
  src/drivers/rtmouse.c
Labels: Type: CI
